---
title: "Data Science Project 1"
date: "`r Sys.Date()`"
author: 
  - "Constantine Zhang"
  - "Ha Nguyen"
  - "Kemal Ege Sural"
output: 
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(results="markup", warning = F, message = F,
                      fig.width=8, fig.height=6, fig.dim=c(8,6), fig.align='center')
options(scientific=T, digits = 3) 
```

```{r library, include = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(tinytex)
library(kableExtra)
```

```{r data import and cleaning na value, include = FALSE}
data_counties <- read.csv("introdata_merged_counties.csv")
data_counties %>% drop_na()
```

```{r preview data}
kable(
  head(data_counties, 5),
  caption = "Table 1. First 5 rows of counties data",
  format = "html",
  align = "c"
) |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = FALSE, position = "center") |>
  scroll_box(width = "100%", height = "300px")
```

```{r data set summary}
summary(data_counties)
```
```{r}
ggplot(data_counties, aes(x = bachelor_degree_numbers_2016_2020, y = per_capita_personal_income_2020 )) +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Bachelor’s Degree Numbers vs. Per Capita Personal Income (2020) Scatter Plot",
    x = "Number of Bachelor's Degree 2016-2020",
    y = "Personal Income Per Capita (2020)"
  ) 

ggplot(data_counties, aes(x = associate_degree_numbers_2016_2020 , y = per_capita_personal_income_2020 )) +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Associate’s Degree Numbers vs. Per Capita Personal Income (2020) Scatter Plot",
    x = "Number of Associate's Degree 2016-2020",
    y = "Personal Income Per Capita (2020)"
  ) 

```

```{r scatter plot after exclude extrem value}
ggplot(data_counties, aes(x = bachelor_degree_numbers_2016_2020, y = per_capita_personal_income_2020 )) +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Bachelor’s Degree Numbers vs. Per Capita Personal Income (2020) 
    Scatter Plot - Exclude extreme value",
    x = "Number of Bachelor's Degree 2016-2020",
    y = "Personal Income Per Capita (2020)" 
  ) + 
  scale_x_continuous(limits = c(0, 150000))  + 
  scale_y_continuous(limits = c(0, 100000))


ggplot(data_counties, aes(x = associate_degree_numbers_2016_2020 , y = per_capita_personal_income_2020 )) +
  geom_point() +
  theme_minimal() +
  labs(
    title = "Associate’s Degree Numbers vs. Per Capita Personal Income (2020) 
    Scatter Plot - Exclude extreme value",
    x = "Number of Associate's Degree 2016-2020",
    y = "Personal Income Per Capita (2020)"
  ) +
  scale_x_continuous(limits = c(0, 150000))  +
  scale_y_continuous(limits = c(0, 100000))

```
```{r exclude extreme value}
# find an metrics for determine extreme values
```






